Increment 22
alexkopcak/shortener pull request #25
Opened 2022-06-26 09:37 UTC by alexkopcak

2022-06-29 10:43 UTC, rktkov requested changes

2022-06-29 10:43 UTC, rktkov commented on internal/storage/storage.go
> +	//ps, err := sql.Open("pgx", cfg.DBConnectionString)
Лишние комментарии надо удалять.

2022-06-29 10:43 UTC, rktkov commented on internal/storage/storage.go
> +// close postgres connection.
Согласно рекомендации по документированию кода, комментарий должен начинаться с имени сущности, которая описывается (с учетом регистра первой буквы).

2022-06-29 10:43 UTC, rktkov commented on internal/app/app.go
>  		Handler: handlers.URLHandler(repository, cfg, dChannel),
Так как файла handlers нет в ПР, поэтому комментирую здесь.
Следуя рекомендациям, если метод/функция принимает экземпляр объекта контекс в виде аргумента, то этот аргумент должен быть первым в списке метода/функции (в данном случае он второй).

2022-06-29 10:43 UTC, rktkov commented on cmd/shortener/main.go
> +	cfgFileName := os.Getenv(envConfigFile)
Работу с конфигурацией стоит вынести в отдельную функцию и поместить ее в пакет  config.

2022-06-30 10:37 UTC, alexkopcak commented on internal/app/app.go
>  		Handler: handlers.URLHandler(repository, cfg, dChannel),
Вы имеете ввиду аргумент с именем cfg? Экземпляр объекта с именем cfg в моей реализации является экземпляром объекта типа Config из пакета config.

2022-07-03 11:24 UTC, rktkov approved these changes

2022-07-06 04:54 UTC, merged